[package]
name = "test-cargo-out-dir-with-build-script"
version = "0.1.0"
authors = ["Robert Chiniquy <robert.chiniquy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
